# Generated by Django 5.2.8 on 2025-11-18 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0018_auto_20211028_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 18, 11, 33, 52, 661408)),
        ),
    ]
